# Managed by https://git.rcmd.space/rcmd/dustbag
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9113']
  - job_name: 'fermium'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.8.0.102:9100']
  - job_name: 'fermium-ng'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.200.200.5:9100']
  - job_name: 'printer'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.200.200.7:9100']
  - job_name: 'vpnserver'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.200.1.2:9100']
  - job_name: 'fermium-smartmontools'
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['10.200.200.5:9633']
  - job_name: 'dafuq'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['127.0.0.1:8881']
